### ISSUE TITLE
Usage of useFormContext, useFieldArray and Controller

### ISSUE THREAD

**Issue by EkaterinaMozheiko** [react-hook-form/react-hook-form#1229]
Hi, 
is it possible to use Controller, useFormContext and useFieldArray together? It seems that formState.dirty doesn't work correctly in this case - it isn't updated when I add or remove a field.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-9z0ur

**Comment by bluebill1049** [comment]
This should fix the problem: https://codesandbox.io/s/react-hook-form-usefieldarray-s3nxp working on solution.

**Comment by IronSean** [comment]
I'm still seeing behaviour like this where the fields inside my array are being edited, appear as touched on the form state, but the form state is not going dirty

**Comment by bluebill1049** [comment]
@IronSean can you supply a CSB for me to investigate?
