### ISSUE TITLE
fields from useFieldArray not updated after calling reset

### ISSUE THREAD

**Issue by ahmad-medhat** [react-hook-form/react-hook-form#1404]
**Describe the bug**
When using reset after an async request in case I have an array from (useFieldArray), the array is not getting populated.

**To Reproduce**
1. Waiting for timeout to finish
2. The list is not getting updated after calling reset

**Codesandbox link (Required)**
https://codesandbox.io/s/gifted-allen-o6utk?file=/src/App.js

**Expected behavior**
After calling reset, fields should be updated to reflect the new data

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 75.0

**Comment by bluebill1049** [comment]
@bluebill1049 unfortunately have to re-open this issue along with something going on with `reset()`:

Please visit the codesandbox below:

https://codesandbox.io/s/issue-rhf-values-v541-f7ye2?file=/src/App.js

1. Open console
2. click delete
3. notice the field array key is missing (console logging twice) before showing correct value
![Screen Shot 2020-04-13 at 4 48 05 PM](https://user-images.githubusercontent.com/10138447/79160024-18f5e500-7da7-11ea-83a7-6dbe4b78bb5f.png)
4. click submit (the button is being conditionally shows when form is dirty)
5. notice error


In v5.3.1 we were able to use `reset(values)` on submit to reset the form state with the new values.  As you can see from this example, there appears to be a problem with the functionality of using `reset(values)`.  Please let me know if you need anymore details.  Thanks!

**Comment by bluebill1049** [comment]
@ahmad-medhat please take a look the following, let me know if fix the issue
https://codesandbox.io/s/quizzical-grass-dfgng?file=/src/src/useFieldArray.ts:0-13528

hey @jonwaldstein can you take a look this quick fix as well? i haven't got enough time to verify the fix, i will take a look again during lunch break or tonight.
https://codesandbox.io/s/issue-rhf-values-v541-p023z?file=/src/App.js

**Comment by jonwaldstein** [comment]
Hey @bluebill1049 Thanks for jumping in!

I just tested the [link](https://codesandbox.io/s/issue-rhf-values-v541-p023z?file=/src/App.js) you shared, but unfortunately the problems still persist 😢

**Comment by bluebill1049** [comment]
thanks @jonwaldstein i will follow your steps above later on.

**Comment by bluebill1049** [comment]
@jonwaldstein this should fix it: https://codesandbox.io/s/issue-rhf-values-v541-p023z?file=/src/src/useFieldArray.ts

**Comment by bluebill1049** [comment]
If everything works, i will add some tests tonight to lock those behaviors, so it doesn't break again.

**Comment by jonwaldstein** [comment]
@bluebill1049, Okay that fixed the first issue (deleting field array in watch). Awesome!

There is still an issue with `reset(values)` - it seems to cause an error when you delete an item from the field array and then submit the form.

![Screen Shot 2020-04-13 at 9 08 49 PM](https://user-images.githubusercontent.com/10138447/79175214-1907dc00-7dcb-11ea-93f6-43de44b643f1.png)

**Comment by bluebill1049** [comment]
thanks @jonwaldstein can you list the steps? i will take a look.

**Comment by jonwaldstein** [comment]
Sure!

https://codesandbox.io/s/issue-rhf-values-v541-p023z?file=/src/src/useFieldArray.ts

**Steps for [Error](https://github.com/react-hook-form/react-hook-form/issues/1404#issuecomment-613171755)**
1. click delete 
2. click submit
3. see error

**Steps for other weird behavior**
1. Click append
2. Click submit
3. notice in console `allWatchedValues` is showing default values first before showing accurate values
![Screen Shot 2020-04-13 at 9 15 58 PM](https://user-images.githubusercontent.com/10138447/79175656-4b660900-7dcc-11ea-92ad-8055d9f379a5.png)

**Comment by bluebill1049** [comment]
Notice 3 is due to 

```
const onSubmit = values => {
    console.log(
      "%c submit clicked",
      "background: #ec5990; color: white; display: block;"
    );
    console.log("onSubmit Values", values);
    reset(values); // this line
  };
```

in side react hook form we do invoke native HTML reset, which leads the form to be empty value and hence defaultValues gets print out from `watch()`;

**Comment by ahmad-medhat** [comment]
Hello @bluebill1049 
Thank you for your time to solve the problem.

The [link ](https://codesandbox.io/s/quizzical-grass-dfgng?file=/src/src/useFieldArray.ts:0-13528)you shared is working regarding populating and re-rendering the fields!

But there is still a small issue. 

**Bug**
After using reset, the fields are rendered but without the correct content.

Codesandbox link (Required)
https://codesandbox.io/s/mutable-surf-ep523?file=/src/App.js

**To Reproduce**
Steps to reproduce the behavior:
1. After intiliazing the default values, you will see one input with name: "Test"
2. After waiting 2 seconds, the fields will re-render but the names are not shown

**Comment by bluebill1049** [comment]
Thanks @ahmad-medhat you are missing `defaultValue`

**Comment by ahmad-medhat** [comment]
Thanks @bluebill1049. It is all good now ☺️

**Comment by bluebill1049** [comment]
I am releasing a version patch the issue now.
