### ISSUE TITLE
Controller component with Draft.js

### ISSUE THREAD

**Issue by Eduardobittencourt08** [react-hook-form/react-hook-form#1550]
Hello,

I'm trying to use [draft.js](https://draftjs.org/) with the react-hook-form. I am using the `Controller` component to render the Editor, but with each update in the value a new render is triggered and in long forms this will become a problem.

I would like to know if there is anything to be done in this case or if this rendering fired by the Editor is inevitable.

[Codesandbox](https://codesandbox.io/s/react-hook-form-controller-template-wluvr?file=/src/index.js)

Thank you in advance, and congratulations on the wonderful library

**Comment by bluebill1049** [comment]
I have very little knowledge about draft.js, but why are you mixing custom register with Controller? 

I would probably just use custom register and update date with `setValue`.

I don't see an Editor on the codesandbox as well, so i guess the usage of Draftjs is probably wrong as well.

**Comment by vensauro** [comment]
Looks that Draft.js use prop value with the name editorState, so you can use the prop `valueName` of controller to use this with Draft.js
Like: [CodeSandbox](https://codesandbox.io/s/twilight-currying-5lvsq?file=/src/index.js)

i too modified the `onChange` to works, 
```
<Controller
    as={<Editor ref={editorRef} />}
    name="draft"
    valueName="editorState"
    onChange={([value]) => value}
    control={control}
/>
```

**Comment by Eduardobittencourt08** [comment]
The Editor was on the screen, but I didn't put any style on it, so he had no background, my bad.

My implementation of the Editor wasn't really correct, but the @vensauro solution worked as expected. Thank you for your help guys!

**Comment by daveteu** [comment]
> Looks that Draft.js use prop value with the name editorState, so you can use the prop `valueName` of controller to use this with Draft.js
> Like: [CodeSandbox](https://codesandbox.io/s/twilight-currying-5lvsq?file=/src/index.js)
> i too modified the `onChange` to works with the Controller, and the controller makes the form not re render
> 
> ```
> <Controller
>     as={Editor}
>     name="draft"
>     valueName="editorState"
>     onChange={([value]) => value}
>     control={control}
> />
> ```

In the above solution, the valueName returns editorState is an object while the value is in editorState.getCurrentContent()

How do you get the value?

With the current submit solution, the Controller value "draft" does not get sent to the server in the submit handler.

draft is undefined.

**Comment by lukebyrne73** [comment]
@eduardobittencourt  I'm trying to do the same here and @vensauro's implementation won't work for me. Getting the error: "Cannot read property 'getCurrentContent' of undefined".

**Comment by vensauro** [comment]
> @eduardobittencourt I'm trying to do the same here and @vensauro's implementation won't work for me. Getting the error: "Cannot read property 'getCurrentContent' of undefined".

this is resolved? what version of RHF are you using

**Comment by bluebill1049** [comment]
@vensauro i did a simple example: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r not sure if this works?

**Comment by lukebyrne73** [comment]
> > eduardobittencourt I'm trying to do the same here and @vensauro's implementation won't work for me. Getting the error: "Cannot read property 'getCurrentContent' of undefined".
> 
> @lukebyrne73
> this is resolved? what version of RHF are you using

@vensauro not resolved for me yet. here is a CodeSandbox link: https://codesandbox.io/s/magical-leftpad-hm571?file=/src/App.js

**Comment by bluebill1049** [comment]
@lukebyrne73 can you fork my codesandbox and work on top it? see if you can get it working?
