### ISSUE TITLE
MUI TextField Label Doesn't Shrink on setValue

### ISSUE THREAD

**Issue by minhaferzz** [react-hook-form/react-hook-form#220]
**Describe the bug**
When doing a setValue for a Material-UI textfield, the label doesn't shrink as expected.

**To Reproduce**
https://codesandbox.io/s/react-hook-form-mui-textfield-3czpw

**Expected behavior**
Label to shrink when data is being set.

**Additional context**
Not at all sure if this is a react-hook-form problem or a Material-UI problem, but this started with Material-UI version 4.2.1 and up. Version 4.2.0 and down seems to work fine.

**Comment by stramel** [comment]
I don't believe this is an issue with `react-hook-form` especially since it worked in previous versions. I'm assuming they modified the internal wiring of events. 

I'm not sure if your codesandbox is an example of what you are trying to do or just demonstrating the issue. However, if you are just trying to set an initial value, you can use the `defaultValue` prop on the `TextField`. 

I will try to take a look into what they changed between 4.2.0 and 4.2.1.

**Comment by minhaferzz** [comment]
@stramel In my use case, I'm getting values from the backend and setting the value after receiving it.

**Comment by stramel** [comment]
It does appear they made some changes but i'm unsure how they would prevent that from working. https://github.com/mui-org/material-ui/compare/v4.2.0...v4.2.1#diff-1f94c95b4e8094138b96211b29be700e

**Comment by oliviertassinari** [comment]
Could the problem come from https://github.com/mui-org/material-ui/pull/16526?

**Comment by stramel** [comment]
Just for referene, MUI related upstream issue https://github.com/mui-org/material-ui/issues/17018

**Comment by stramel** [comment]
@oliviertassinari That's basically the only InputBase code changes that I noticed. I would assume it has to be within that. Maybe the `checkDirty` removal?

**Comment by oliviertassinari** [comment]
Very possible, I don't really understand how this plugin work in the first place. The only way I can picture it work is by bypassing React, using the DOM input element directly.

Ideally, I wish we had a failing test case we can work with.

**Comment by stramel** [comment]
@oliviertassinari Correct. basically, we use the DOM input ref to attach event listeners directly. I will see if I can write a failing test for your UI lib.

**Comment by oliviertassinari** [comment]
Thanks, for instance, you could try to add the check dirty logic back. If it fixes the integration. You could then try to add one of the test cases we have removed, see if it fails without the check dirty logic. Does it make sense?

**Comment by stramel** [comment]
Yes, thank you for providing some direction.

**Comment by stramel** [comment]
@oliviertassinari It does fix it when I re-add the `checkDirty` back in for the uncontrolled inputs. I will open a PR with a failing test and then add a fix.

**Comment by oliviertassinari** [comment]
Sounds great!

**Comment by stramel** [comment]
Fix submitted upstream 👍

**Comment by bluebill1049** [comment]
Thanks @oliviertassinari and @stramel for addressing this issue ❤️

**Comment by bluebill1049** [comment]
@minhaferzz you happy to close this issue?

**Comment by minhaferzz** [comment]
Thanks everyone!

**Comment by oliviertassinari** [comment]
The issue is not solved yet.

**Comment by bluebill1049** [comment]
@oliviertassinari what's the remaining issue? I thought @stramel already submitted a PR for this issue.

**Comment by oliviertassinari** [comment]
The latest comment by @eps1lon suggest that the best solution might be applied here.

**Comment by bluebill1049** [comment]
@oliviertassinari sure can I have bit more detail in terms the fix?

**Comment by oliviertassinari** [comment]
The concern is expresse in https://github.com/mui-org/material-ui/issues/17018#issuecomment-522869193

**Comment by bluebill1049** [comment]
@minhaferzz sorry looks like the change are not been merged (https://github.com/mui-org/material-ui/pull/17025) :( hopefully, react hook form gets more popular, so MUI will consider to re-evaluating. I wish I could do something about it but unfortunately, it's a little bit out of my hand at this state. :(

**Comment by bluebill1049** [comment]
Since MUI is probably not going to support RHF for now, one of the options that I could think of is to use the custom register. Basically, register during `useEffect` without the `ref`.

**Comment by jwthanh** [comment]
```
<TextField
          variant="outlined"
          margin="normal"
          required
          fullWidth
          id="username"
          label="Username"
          name="username"
          autoFocus
          inputRef={register}
        />
```
using `inputRef={register}` will resolve

**Comment by bluebill1049** [comment]
thanks, @jwthanh, it's a problem with `setValue` currently MUI doesn't support changing the value via input `ref`. so if you are not using `setValue` you should be fine with what you supplied.

**Comment by bluebill1049** [comment]
I am going to close this issue for now. feel free to add more questions in here. hopefully one day this lib gets more popular, MUI will consider supporting :)

**Comment by wortkotze** [comment]
Is there any fix by now. I really love RHF but for us MUI is an important Component Libary that needs to be supported. Is there any workaround. The rest is really working fine beside this issue with the label. For us its an important usecase to setValues as they are coming from external APIs?

**Comment by bluebill1049** [comment]
@wortkotze This has been fixed/improved since v3 :) 
https://react-hook-form.com/api#Controller

https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by wortkotze** [comment]
hm ok, I was using the documentation from the website. there it was documented to use the innerRef. everything is working only by using setValue the label is not moving away. in your links i did not find any usecase for this :( - sry probably I missed something

**Comment by wortkotze** [comment]
I tried also the Controller version, its stalling in SSR ...

**Comment by jonyw4** [comment]
I have the same problem too using setValue, the label is not moving away... What we can do to work?

**Comment by bluebill1049** [comment]
> I have the same problem too using setValue, the label is not moving away... What we can do to work?

Take a look `Controller` https://codesandbox.io/s/react-hook-form-controller-079xx

**Comment by jonyw4** [comment]
> Take a look `Controller` https://codesandbox.io/s/react-hook-form-controller-079xx

Yeah, MUI works generally well, but take a look in this example:
https://codesandbox.io/s/react-hook-from-mui-setvalue-label-bug-0z5z3

I create an example using a `setValue` in every time that the field postalCode changes. Notice that when i use `setValue` the label doesn't go up. Maybe its a MUI bug, but I don't know...

**Comment by bluebill1049** [comment]
> > Take a look `Controller` https://codesandbox.io/s/react-hook-form-controller-079xx
> 
> Yeah, MUI works generally well, but take a look in this example:
> https://codesandbox.io/s/react-hook-from-mui-setvalue-label-bug-0z5z3
> 
> I create an example using a `setValue` in every time that the field postalCode changes. Notice that when i use `setValue` the label doesn't go up. Maybe its a MUI bug, but I don't know...

I think you are missing defaultValue: https://codesandbox.io/s/react-hook-from-mui-setvalue-label-bug-v3bwo

**Comment by jonyw4** [comment]
@bluebill1049 Thanks!!! This solves the issue. Using `Controller` with `defaultValue` for MUI works great!!!

**Comment by eladams** [comment]
This issue also occurs (MUI v4.11) when initializing the Input with undefined/null, if you initialize it with an empty string the dirty check will work as expected.

**Comment by hypercubex** [comment]
tried and added `InputLabelProps={{ shrink: true }}` to the TextField and it worked for me
example:
https://codesandbox.io/s/react-hook-form-mui-textfield-forked-jxop5

**Comment by efendi-klb** [comment]
same condition, i fixed it with set the textfield's defaultvalue to empty string, works well

**Comment by pnam29** [comment]
> tried and added `InputLabelProps={{ shrink: true }}` to the TextField and it worked for me example: https://codesandbox.io/s/react-hook-form-mui-textfield-forked-jxop5

it work, thanks

**Comment by charesbast** [comment]
Well, adding this prop `InputLabelProps={{ shrink: true }}` does not solve the problem if you want to keep the original behaviour (having the label inside the input when there is no value)

**Comment by darren10201** [comment]
If anyone still sturggling, the 2022 answer is 

`    <Controller
                        control={control}
                        name="state"
                        render={(fields) => (
                          <TextField
                            {...fields}
                            value={fields.field.value}
                            InputLabelProps={{ shrink: fields.field.value ? true : false }}
                            defaultValue=""
                            size="small"
                            required
                            label="State"
                            placeholder="Ex: New York"
                          />
                        )}
                      />`

**Comment by MetaMmodern** [comment]
The solution is great, though it is kinda bulky. I'm currently making a pretty small form, around 6 textFields and the return JSX looks already awful(I'm not even using Controller yet). I'm not using validator and typescript, but I think after adding those the code may shrink to about 15-20%. If I start using `Controller` I'd expect the return value to expand to about 40-50%. Can someone tell if it's a normal situation to have a form 200+ lines of JSX long?

**Comment by MetaMmodern** [comment]
To not look judgemental I'm leaving a solution, that worked for me. May fit those who don't want to use Controller for some reason. It's still +line, but at least it's laconic and self-explanatory.

```js
const { register, watch } = useForm()

return (
  <form>
        <TextField
            name={'name'}
            label={'Name'}
            inputRef={register()}
            InputLabelProps={{ shrink: !!watch('name') }}
          />
  </form>
)
```

Yep, just use `watch` to set the shrink state.
I tried using `getValues` since I know watch constantly listens to form updates and may overload your website if not used correctly, but I think since it's a function component and watch is called in return statement it should self-eliminate on every rerender. (@bluebill1049 correct me here if I'm wrong)

**Comment by eliellima00** [comment]
I found one solution, it works for me, but I don't know if it is the best way to do this
`<Controller
              name="desafiosAtuais"
              control={control}
              render={({ field }) => (
                <TextFieldGeral
                  {...field}
                  value={field.value ? field.value : ""}
                  variant="standard"
                  fullWidth
                  label="Descreva seus desafios atuais"
                />
              )}
            />`

**Comment by linhvanphuong** [comment]
> To not look judgemental I'm leaving a solution, that worked for me. May fit those who don't want to use Controller for some reason. It's still +line, but at least it's laconic and self-explanatory.
> 
> ```js
> const { register, watch } = useForm()
> 
> return (
>   <form>
>         <TextField
>             name={'name'}
>             label={'Name'}
>             inputRef={register()}
>             InputLabelProps={{ shrink: !!watch('name') }}
>           />
>   </form>
> )
> ```
> 
> Yep, just use `watch` to set the shrink state. I tried using `getValues` since I know watch constantly listens to form updates and may overload your website if not used correctly, but I think since it's a function component and watch is called in return statement it should self-eliminate on every rerender. (@bluebill1049 correct me here if I'm wrong)

This realy work for me. Thanks a lot sir!

**Comment by MetaMmodern** [comment]
> > To not look judgemental I'm leaving a solution, that worked for me. May fit those who don't want to use Controller for some reason. It's still +line, but at least it's laconic and self-explanatory.
> > ```js
> > const { register, watch } = useForm()
> > 
> > return (
> >   <form>
> >         <TextField
> >             name={'name'}
> >             label={'Name'}
> >             inputRef={register()}
> >             InputLabelProps={{ shrink: !!watch('name') }}
> >           />
> >   </form>
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yep, just use `watch` to set the shrink state. I tried using `getValues` since I know watch constantly listens to form updates and may overload your website if not used correctly, but I think since it's a function component and watch is called in return statement it should self-eliminate on every rerender. (@bluebill1049 correct me here if I'm wrong)
> 
> This realy work for me. Thanks a lot sir!

You're welcome. Can you imagine: I'm on another project now and I came to this problem again and I found this thread and applied my own suggestion hahahah) Past me is literally helping current me😂😂😂

**Comment by MetaMmodern** [comment]
Actually, I've just made a little reproduction: 
https://codesandbox.io/s/mui-textfield-label-not-shrinking-rhf-dibrid

Can anyone check it out? When I call setValue in any asyncronous task it doesn't shrink the label. (For instance same would happen if I made fetch and set value in a `then`callback)

@bluebill1049 can you please check it? This is currently the root issue for me, since I use refine to build admin panel, and it has a wrapper hook for your `useForm`, which fetches different resources from backend. But the core is the same as yours.

I don't know if I should duplicate this in MUI thread.

**Comment by MdeMora** [comment]
I've been able to solve this issue without using `watch` in the case anyone is concerned about the performance of their form. I hope anyone find this helpful

```
<Controller
          control={control}
          name="example"
          render={({field: {onChange, value}}) => (
            <TextField
              onChange={onChange}
              value={value || ''}
              label="My Label"
            />
          )}
        />
```
