### ISSUE TITLE
setValue()'s first parameter is always of type 'never' in Typescript

### ISSUE THREAD

**Issue by beepsoft** [react-hook-form/react-hook-form#297]
**Describe the bug**
I try to use react-hook-form in Typescript. The IDE (IntelliJ in my case but also the Typescript compiler) complains that 

```Argument of type "..." is not assignable to parameter of type never```

**To Reproduce**

Here's a simple codesandbox project. Open it in the Editor, wait a bit and you will see that in line index.tsx:8 "someField" will be marked red and mouse over will show

```Argument of type "someField" is not assignable to parameter of type never```

https://codesandbox.io/embed/react-typescript-vf3xc

The same thing happens in IntelliJ as well.

If you mouse over on useForm in index.tsx:6 the second type argument there will also be 'never'.

**Comment by stramel** [comment]
@beepsoft 	Your codesandbox is giving errors about crossorigin errors. However, if you pass the generic to `useForm` it should not give you any errors. In your case, `useForm<{ someField: string }>()` should get rid of the error. It shouldn't require the generic so I can look into that if you can provide a codesandbox that doesn't trigger cors errors.

**Comment by beepsoft** [comment]
Thanks @stramel! I know the example itself doesn't run but I just wanted to demonstrate the editing/IDE problem.

**Comment by bluebill1049** [comment]
@stramel is there any way we can improve on it?

**Comment by stramel** [comment]
@bluebill1049 Yeah, we _shouldn't_ require passing a generic. I think if I improve the typing to where the key extends string it should be fine. Will look into it.

**Comment by bluebill1049** [comment]
I have a PR on my way, it probably will solve this issue

**Comment by bluebill1049** [comment]
can you test `3.23.6-beta.3` see if it resolve your issue @beepsoft

**Comment by beepsoft** [comment]
`3.23.6-beta.3` solves the `never` problem, but now for this:

```
    <input
      type="hidden"
      name="start"
      defaultValue={watch(
        "start",
        obj.should_start == null
          ? undefined
          : String(obj.should_start)
      )}
      ref={register({ required: true })}
    />
```

I got this  error 
```
Error:(156, 19) TS2322: Type 'unknown' is not assignable to type 'string | string[] | undefined'.
  Type 'unknown' is not assignable to type 'string[]'.
```

**Comment by bluebill1049** [comment]
thanks @beepsoft  which line was of code is causing this issue?

**Comment by beepsoft** [comment]
The `defaultValue` is marked with red in my IDE. And it is the same no matter if I use `undefined` or  `""` after the `?`.

**Comment by bluebill1049** [comment]
@beepsoft what about remove the `watch` and just place 'start' maybe the return type for `watch`

**Comment by beepsoft** [comment]
@bluebill1049 Well, you know, I had to use it because of this other issue: #284 ;)

**Comment by bluebill1049** [comment]
yea, I want to make sure its the return type of watch cause the issue.

**Comment by beepsoft** [comment]
I see, it is definitely the `watch()` without that there's no TS error.

**Comment by bluebill1049** [comment]
cool will sort it out thanks

**Comment by bluebill1049** [comment]
strange, I tested myself there isn't any error: 
<img width="711" alt="Screen Shot 2019-09-12 at 3 54 35 pm" src="https://user-images.githubusercontent.com/10513364/64757489-a9e8b180-d575-11e9-9b5d-30290738f4a9.png">

**Comment by bluebill1049** [comment]
@beepsoft 

const { register, watch } = useForm<{
      start: string
}>();

if you give start type as string or a type should solve your problem.

**Comment by bluebill1049** [comment]
<img width="718" alt="Screen Shot 2019-09-12 at 4 06 34 pm" src="https://user-images.githubusercontent.com/10513364/64758216-58412680-d577-11e9-8724-3c3fb5b627cb.png">

**Comment by beepsoft** [comment]
I still have the error, but maybe I'm doing something wrong. Can you please give me the codesandbox for the above example?

**Comment by bluebill1049** [comment]
nvm it's my fault, I did adjust the return type by remove `void` next patch should solve your problem.

```
import useForm from "./src";

export default function Test() {
  const { register, watch } = useForm<{
      start: string
  }>();

  const obj = { should_start: true };

  return (
    <input
      name="start"
      ref={register}
      defaultValue={watch(
        "start",
        obj.should_start == null ? undefined : String(obj.should_start)
      )}
    />
  );
}
```

**Comment by bluebill1049** [comment]
I have published `v3.23.6`, this should be a good patch for you.

**Comment by beepsoft** [comment]
I just tried with v3.23.7 and I still get this for the `defaultValue={watch(...`:

```
Error:(156, 19) TS2322: Type 'unknown' is not assignable to type 'string | string[] | undefined'.
  Type 'unknown' is not assignable to type 'string[]'.
```

**Comment by beepsoft** [comment]
But using useForm with properly defined type is really a good idea and I use it now like that and in that case it works perfectly.

**Comment by bluebill1049** [comment]
cool glad it works now 🙏

**Comment by JaredDahlke** [comment]
if anyone is still having this problem even with properly typed form like me, this solved it for me:

setValue('firstName', val as never)
