### ISSUE TITLE
Getting 'Cannot read property 'id' of undefined` when adding fields using useFieldArray in latest update

### ISSUE THREAD

**Issue by pixel-mattp** [react-hook-form/react-hook-form#3859]
**Describe the bug**
Field arrays have broken since updating to the latest version of RHF.  
When adding a field using `append()` and `useFieldArray`, we get the following error:

`Cannot read property 'id' of undefined`.

**To Reproduce**

Visit https://codesandbox.io/s/intelligent-shannon-cydr3?file=/src/App.js

1. Click 'Add new field'
2. See error

**Codesandbox link (Required)**
Visit https://codesandbox.io/s/intelligent-shannon-cydr3?file=/src/App.js

**Expected behavior**
Fields should be added as per expected behaviour

Using RHF version 6.14.1

**Comment by bluebill1049** [comment]
https://react-hook-form.com/api#useFieldArray

type for append: `(obj: object | object[], shouldFocus: boolean = true) => void` 

it's not optional.

**Comment by pixel-mattp** [comment]
Seemed to have missed this in the updates since.  Thanks for the hint.  Fixed now.

**Comment by kyunghwa5** [comment]
The issue is still there. I'm using version 7.20.4. It only partially generates the id, not all of them in my case. I've tried also giving a different keyName but didn't work.
