### ISSUE TITLE
issue: setValue with shouldDirty and shouldTouch combine not update state correctly

### ISSUE THREAD

**Issue by Moshyfawn** [react-hook-form/react-hook-form#7506]
### Version Number

7.22.5

### Codesandbox/Expo snack

https://codesandbox.io/s/should-dirty-fail-qnsfm

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/s/should-dirty-fail-qnsfm)
2. Click on "John" button
3. See `firstName` input `Dirty` field in devtools not set to true

### Expected behaviour

The `firstName` field is set as **dirty**

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
thank you @Moshyfawn.

**Comment by bluebill1049** [comment]
fixed: https://github.com/react-hook-form/react-hook-form/pull/7508

**Comment by lecoqjacob** [comment]
I believe the issue is still occuring. Using the sandbox from above and changing the react-hook-version to `v7.230` it still doesnt set both

**Comment by Moshyfawn** [comment]
> @bluebill1049 I believe the issue is still occuring. Using the sandbox from above and changing the react-hook-version to `v7.230` it still doesnt set both

Yep, I thought it's the Codesandbox package versions cache issue, but can reproduce in a local environment

**Comment by bluebill1049** [comment]
not released yet.
