### ISSUE TITLE
issue: `defaultChecked` not respecting the defaultValues priority

### ISSUE THREAD

**Issue by cloud-walker** [react-hook-form/react-hook-form#7900]
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-defaultchecked-bug-4vu372

### Steps to reproduce

Just watch the first render of the forms

### Expected behaviour

The `defaultValues` passed from the props should win over the inline `defaultValue` / `defaultChecked`, but `defaultChecked` seems to ignore this when set to `true`

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cloud-walker** [comment]
The seems to be there until the v7.1

**Comment by Moshyfawn** [comment]
You're right, fixed in [v7.1.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.1.0). You should upgrade to [v7.1.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.1.0) or higher

**Comment by cloud-walker** [comment]
Hi @Moshyfawn I'm already in the v7.27.1, I'm saying that the bug is **until** the v7.1 onward, the bug is still there

**Comment by bluebill1049** [comment]
I would suggest not going into the win over inline vs `defaultValues`, it should be either in terms of usage. This applies to most of the usage in the lib, eg useContollrer

> You need to either set defaultValue at the field-level or useForm's defaultValues. undefined is not a valid value.

right now, the inline `defaultChecked` is required to check before we apply values from defaultValues.

**Comment by cloud-walker** [comment]
So .. I'm not entirely sure I understand your statement 🤔

Are you suggesting to use `defaultValues` or `defaultChecked | defaultValue` but not both combined?

(My way to build the forms has been to use inline default values by default and use `defaultValues` to inject default values from the outside as a prop.)

**Comment by bluebill1049** [comment]
> Are you suggesting to use defaultValues or defaultChecked | defaultValue but not both combined?

yes, it's better that way.
