### ISSUE TITLE
issue: `Control` type regression

### ISSUE THREAD

**Issue by nicobatalla** [react-hook-form/react-hook-form#8689]
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/youthful-elion-r6wrtw?file=/src/App.tsx

### Problem description

In our prod application, we have a **SharedFields** component that renders some standard fields that several forms use. In order to do this, we pass a `control` prop that we take from the result of each `useForm()` hook. Since we don't know the exact form data type, we use `Control<any>` for this prop type. This was working fine up to 7.33.0, but now TS throws an error.

### Steps to reproduce

1. Go to App.tsx
2. See the error on SharedFields control prop.

This same code example works fine up to 7.33.0.

### Expected behaviour

`Control` type should be able to handle generic types.

### Relevant log output

```shell
Type 'Control<FormValues, object>' is not assignable to type 'Control<any, any>'.
  The types of '_subjects.state' are incompatible between these types.
    Type 'FormStateSubjectRef<FormValues>' is not assignable to type 'FormStateSubjectRef<any>'.
      Type 'FormStateSubjectRef<FormValues>' is not assignable to type '{ readonly observers: Observer<Partial<FormState<any>> & { name?: string | undefined; }>[]; subscribe: (value: Observer<Partial<FormState<any>> & { ...; }>) => Subscription; unsubscribe: Noop; }'.
        Types of property 'subscribe' are incompatible.
          Type '(value: Observer<Partial<FormState<FormValues>> & { name?: string | undefined; }>) => Subscription' is not assignable to type '(value: Observer<Partial<FormState<any>> & { name?: string | undefined; }>) => Subscription'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'Observer<Partial<FormState<any>> & { name?: string | undefined; }>' is not assignable to type 'Observer<Partial<FormState<FormValues>> & { name?: string | undefined; }>'.
                Type 'Partial<FormState<FormValues>> & { name?: string | undefined; }' is not assignable to type 'Partial<FormState<any>> & { name?: string | undefined; }'.
                  Type 'Partial<FormState<FormValues>> & { name?: string | undefined; }' is not assignable to type 'Partial<FormState<any>>'.
                    Types of property 'errors' are incompatible.
                      Type 'FieldErrorsImpl<DeepRequired<FormValues>> | undefined' is not assignable to type 'FieldErrorsImpl<DeepRequired<any>> | undefined'.
                        Type 'FieldErrorsImpl<DeepRequired<FormValues>>' is not assignable to type 'FieldErrorsImpl<DeepRequired<any>>'.
                          Property 'otherField' is incompatible with index signature.
                            Type 'FieldError' is not assignable to type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>>'.
                              Property 'type' is incompatible with index signature.
                                Type 'LiteralUnion<"pattern" | "valueAsNumber" | "valueAsDate" | "setValueAs" | "disabled" | "required" | "min" | "max" | "maxLength" | "minLength" | "validate" | "value" | "shouldUnregister" | "onChange" | "onBlur" | "deps", string>' is not assignable to type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined'.
                                  Type '"pattern"' is not assignable to type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined'.ts(2322)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
`Control<any, object>` should fix it, your usage is skipping all the type checks.

**Comment by nicobatalla** [comment]
> `Control<any, object>` should fix it, your usage is skipping all the type checks.

Nope, still happens when using `Control<any, check>`. I actually updated the codesanbox to use that typing, but I still get the same issue.

**Comment by JonKrone** [comment]
@bluebill1049 We are also seeing this problem in a similar situation to Nico, in our case passing `control` to a custom Dropdown component where we then `useController` to hook into form state.

Changing to `Control<any, object>`, or applying the diff in your PR here, https://github.com/react-hook-form/react-hook-form/commit/33820e6fcfb5c817eadf013f6d975ab15665e514, does not fix the issue.

**Comment by gstvds** [comment]
I'm having this problem too. I tried to apply the https://github.com/react-hook-form/react-hook-form/commit/33820e6fcfb5c817eadf013f6d975ab15665e514 but it doesn't fix the issue as well.

**Comment by bluebill1049** [comment]
@gstvds that's pretty much the revert. will release it this week.

**Comment by nicobatalla** [comment]
Unfortunately, this still happens on `7.34.0`. Can we reopen the issue? @bluebill1049 

I updated the codesandbox to point to `7.34.0`.

This is the log we are getting now:

```ts
Type 'Control<FormValues, any>' is not assignable to type 'Control<FieldValues, any>'.
  The types of '_subjects.state' are incompatible between these types.
    Type 'FormStateSubjectRef<FormValues>' is not assignable to type 'FormStateSubjectRef<FieldValues>'.
      Type 'FormStateSubjectRef<FormValues>' is not assignable to type '{ readonly observers: Observer<Partial<FormState<FieldValues>> & { name?: string | undefined; }>[]; subscribe: (value: Observer<Partial<FormState<FieldValues>> & { ...; }>) => Subscription; unsubscribe: Noop; }'.
        Types of property 'subscribe' are incompatible.
          Type '(value: Observer<Partial<FormState<FormValues>> & { name?: string | undefined; }>) => Subscription' is not assignable to type '(value: Observer<Partial<FormState<FieldValues>> & { name?: string | undefined; }>) => Subscription'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'Observer<Partial<FormState<FieldValues>> & { name?: string | undefined; }>' is not assignable to type 'Observer<Partial<FormState<FormValues>> & { name?: string | undefined; }>'.
                Type 'Partial<FormState<FormValues>> & { name?: string | undefined; }' is not assignable to type 'Partial<FormState<FieldValues>> & { name?: string | undefined; }'.
                  Type 'Partial<FormState<FormValues>> & { name?: string | undefined; }' is not assignable to type 'Partial<FormState<FieldValues>>'.
                    Types of property 'errors' are incompatible.
                      Type 'FieldErrorsImpl<DeepRequired<FormValues>> | undefined' is not assignable to type 'FieldErrorsImpl<DeepRequired<FieldValues>> | undefined'.
                        Type 'FieldErrorsImpl<DeepRequired<FormValues>>' is not assignable to type 'FieldErrorsImpl<DeepRequired<FieldValues>>'.
                          Property 'otherField' is incompatible with index signature.
                            Type 'FieldError' is not assignable to type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>>'.
                              Property 'type' is incompatible with index signature.
                                Type 'LiteralUnion<"pattern" | "required" | "min" | "max" | "maxLength" | "minLength" | "validate" | "valueAsNumber" | "valueAsDate" | "value" | "setValueAs" | "shouldUnregister" | "onChange" | "onBlur" | "disabled" | "deps", string>' is not assignable to type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined'.
                                  Type '"pattern"' is not assignable to type 'Merge<FieldError, FieldErrorsImpl<DeepRequired<any>>> | undefined'.ts(2322)
```

**Comment by bluebill1049** [comment]
I did a deeper look at this issue. This can not be resolved with the newly updated field errors type, you are skipping the type check for the control so you will have to simply set it to `any`.

**Comment by meotimdihia** [comment]
Hi, then how to solve this problem? I don't understand what @bluebill1049 was talking about.
There is my problem https://stackblitz.com/edit/next-typescript-pokptk-wuiput?file=pages%2Finput2.tsx,pages%2Findex.tsx
I appreciate it if someone takes a look at my problem.
I am not really good with Typescript.
